tap "homebrew/bundle"
cask "iterm2"
cask "openvpn-connect"
cask "intune-company-portal"
cask "1password"
cask "discord"
cask "github"
cask "remote desktop manager"
cask "spotify"
cask "snagit"
cask "signal"
cask "telegram"
cask "yubico authenticator"
cask "visual-studio-code"
