tap "homebrew/bundle"
cask "1password"
cask "1password-cli"
cask "discord"
cask "iterm2"
cask "displaylink"
cask "firefox@esr"
cask "powershell"
cask "imazing-profile-editor"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-teams"
cask "remote-desktop-manager"
cask "remoteviewer"
cask "signal"
cask "slack"
cask "snagit"
cask "sonos"
cask "spotify"
cask "telegram"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "windows-app"

Missing:
netbird
